"""Helper script to guide Google Custom Search API setup."""

print("=" * 70)
print("Google Custom Search API Setup Guide")
print("=" * 70)
print("")
print("You have the API Key ✅")
print("Now you need the Search Engine ID (CX)")
print("")
print("Steps to get Search Engine ID:")
print("")
print("1. Go to: https://programmablesearchengine.google.com/controlpanel/all")
print("")
print("2. Click 'Add' to create a new search engine")
print("")
print("3. Configure:")
print("   - Sites to search: Leave blank OR enter '*.gov' (to search only .gov sites)")
print("   - Name: 'Municipal Permit Portals' (or any name)")
print("   - Click 'Create'")
print("")
print("4. After creation, you'll see your Search Engine ID")
print("   - It looks like: 012345678901234567890:abcdefghijk")
print("   - This is the 'cx' parameter")
print("")
print("5. Add to .env file:")
print("   GOOGLE_CUSTOM_SEARCH_ENGINE_ID=your_engine_id_here")
print("")
print("6. Then test with:")
print("   poetry run python scripts/phase1_4/test_portal_discovery.py")
print("")
print("=" * 70)
print("Alternative: Test with just API key (will show what's missing)")
print("=" * 70)
